In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./EasyVisa.csv")

In [4]:
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [5]:
df.shape

(25480, 12)

In [6]:
df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [7]:
data = df.to_dict(orient="records")

In [8]:
data[0]

{'case_id': 'EZYV01',
 'continent': 'Asia',
 'education_of_employee': 'High School',
 'has_job_experience': 'N',
 'requires_job_training': 'N',
 'no_of_employees': 14513,
 'yr_of_estab': 2007,
 'region_of_employment': 'West',
 'prevailing_wage': 592.2029,
 'unit_of_wage': 'Hour',
 'full_time_position': 'Y',
 'case_status': 'Denied'}

In [9]:
len(data)

25480

In [26]:
import os
import pymongo
from dotenv import load_dotenv

load_dotenv()
DB_NAME = os.getenv("DB_NAME")
COLLECTION_NAME = os.getenv("COLLECTION_NAME")
CONNECTION_URL = os.getenv("CONNECTION_URL")

if not all([DB_NAME, COLLECTION_NAME, CONNECTION_URL]):
    raise ValueError("Missing MongoDB env vars: DB_NAME, COLLECTION_NAME, CONNECTION_URL")

In [18]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

rec = collection.insert_many(data)

In [19]:
records = collection.find()
records

In [20]:
df = pd.DataFrame(list(collection.find()))

In [21]:
df.head()

,_id,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,69cd7cd79cbb73f7bf9c472d,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,69cd7cd79cbb73f7bf9c472e,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,69cd7cd79cbb73f7bf9c472f,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,69cd7cd79cbb73f7bf9c4730,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,69cd7cd79cbb73f7bf9c4731,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [22]:
df.shape

(25480, 13)

In [23]:
if "_id" in df.columns.to_list():
    df = df.drop(columns=["_id"], axis=1)

In [24]:
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified